version: '3.8'

services:
  app:
    build:
      context: .
      target: builder
    command: yarn dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - ./tsconfig.json:/app/tsconfig.json
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
